# Generated by Django 4.1.3 on 2022-11-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_alter_play_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='baseball.club'),
        ),
    ]
